server:
  port: 8052
#注册中心
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: "http://localhost:8051/eureka"
spring:
  application:
    name: com-liu-gateway
  kafka:
    listener:
      poll-timeout: 6000
    producer:
      acks: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "com-liu"
      auto-offset-reset: "earliest"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: "172.31.206.211:9092"
logging:
  level: info

#网关过滤配置
zuul:
  ignore-security-headers: true
  sensitive-headers: "*"
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000